//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StairsVarientBaseCost
    {
        public int Id { get; set; }
        public Nullable<int> MinStair { get; set; }
        public Nullable<int> MaxStair { get; set; }
        public Nullable<double> OverAllCost { get; set; }
    }
}
